name: Update Excel File

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 11:30 AM IST
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

        # Install latest Chrome (you can pin to 145 if needed)
      - name: Install Chrome
        run: |
          choco install googlechrome -y
          choco install chromedriver -y

      - name: Copy ChromeDriver to project path
        shell: pwsh
        run: |
          $driverPath = (Get-ChildItem "C:\ProgramData\chocolatey\lib\chromedriver" -Recurse -Filter "chromedriver.exe" | Select-Object -First 1).FullName
          $targetDir = "$(Get-Location)\Drivers\updated_driver"
          New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
          Copy-Item $driverPath "$targetDir\chromedriver.exe" -Force
          Write-Host "Driver copied to $targetDir\chromedriver.exe"




      - name: Run Maven tests
        run: mvn test

      - name: Commit updated Excel file
        run: |
          git config user.name "karthick-lab"
          git config user.email "karthick.shayee@gmail.com"
          git add src/test/resources/Data/GoldData.xlsx
          git commit -m "Update Excel file from GitHub Actions on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
